dist: trusty  
language: cpp
git:
  depth: false
matrix:
  include:
    - name: Linux GCC
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "L4nEr4rHuk4Le7jFQyAFNVsI+m7rsInUHPwhQMVPfUQq1gYdy2NzijLVY2Y/DMvmuxn0NgI/AN2b/FcY+qD8vWa4tz07BrRL5PAu+uISSQayVdKE7ELS8ENVrwGPIbpuk5RQpBVCpJOn1SbOmjSPcqHwfedLVt6cqAk/mCXbGBQd0As8YhGTDFwFtxXMD1TNwqpXCSLnUQKsatbtAb1BUH6erBCzTvFquevx70S/c0zv40gB1slla5MQwXrs14IQqJT05TQqJVgls5t4p+C4aZg0nZ3XRIGfpNyUkedod3cW7YW8UJX4brzFjqHyA2EiND3um9ov9aj7ZwRtmlavJs6w/cMS+eFBjAQmW3TZythe7oPYFZAc3c86KDQo0z9h836e7Sav/sGz/BvCpEa9ofTJJoROV8TobP2bWWFqoz0hPj3t8PDnuaoEuQeFdAh5ZjIuQ8OcGJrRMKoowqSWLiFs1XSUSvTU6f+Vhm7BWHuZc+FvmnpXxkJfG+0o4hzOSsQuspKhSrcy5bMJAi5rkxnkMheNKQBS8HZ6tpKwlJYVPX8gJQvfCwX6Z+Srfv22mPuWv/JpPG/NKPrxOHDa7aAQx6irGj+oDjucNmu0L9bkMhPuK3eNwtd6m0eoGAxDdq017gvY7EdczF00TbDNpwUDF4cqEeb7Fg5AQ5F48Tc="
      before_install:
        - sudo apt-get install -y libopenal-dev
        - sudo apt-get install -y libasound2-dev
        - sudo apt-get install -y libxi-dev
        - sudo apt-get install -y libxcursor-dev
        - curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-linux.zip -o sonar-scanner-cli-3.3.0.1492-linux.zip
        - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
        - export PATH=$(pwd)/sonar-scanner-3.3.0.1492-linux/bin:$PATH
      before_script:
        - export CXX=g++-6
      script:
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2 -C samples/
        - sonar-scanner -D sonar.projectKey=Ouzel -D sonar.projectName="Ouzel Linux" -D sonar.cfamily.threads=2 || true
    - name: macOS
      compiler: clang
      os: osx
      osx_image: xcode7.3
      addons:
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "L4nEr4rHuk4Le7jFQyAFNVsI+m7rsInUHPwhQMVPfUQq1gYdy2NzijLVY2Y/DMvmuxn0NgI/AN2b/FcY+qD8vWa4tz07BrRL5PAu+uISSQayVdKE7ELS8ENVrwGPIbpuk5RQpBVCpJOn1SbOmjSPcqHwfedLVt6cqAk/mCXbGBQd0As8YhGTDFwFtxXMD1TNwqpXCSLnUQKsatbtAb1BUH6erBCzTvFquevx70S/c0zv40gB1slla5MQwXrs14IQqJT05TQqJVgls5t4p+C4aZg0nZ3XRIGfpNyUkedod3cW7YW8UJX4brzFjqHyA2EiND3um9ov9aj7ZwRtmlavJs6w/cMS+eFBjAQmW3TZythe7oPYFZAc3c86KDQo0z9h836e7Sav/sGz/BvCpEa9ofTJJoROV8TobP2bWWFqoz0hPj3t8PDnuaoEuQeFdAh5ZjIuQ8OcGJrRMKoowqSWLiFs1XSUSvTU6f+Vhm7BWHuZc+FvmnpXxkJfG+0o4hzOSsQuspKhSrcy5bMJAi5rkxnkMheNKQBS8HZ6tpKwlJYVPX8gJQvfCwX6Z+Srfv22mPuWv/JpPG/NKPrxOHDa7aAQx6irGj+oDjucNmu0L9bkMhPuK3eNwtd6m0eoGAxDdq017gvY7EdczF00TbDNpwUDF4cqEeb7Fg5AQ5F48Tc="
      before_install:
        - curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-macosx.zip -o sonar-scanner-cli-3.3.0.1492-macosx.zip
        - unzip sonar-scanner-cli-3.3.0.1492-macosx.zip
        - export PATH=$(pwd)/sonar-scanner-3.3.0.1492-macosx/bin:$PATH
      before_script:
        - export CXX=clang++
      script:
        - build-wrapper-macosx-x86 --out-dir bw-output make -j2 -C samples/
        - sonar-scanner -D sonar.projectKey=OuzelMacOS -D sonar.projectName="Ouzel macOS" -D sonar.cfamily.threads=2 || true
    - name: iOS
      compiler: clang
      os: osx
      osx_image: xcode7.3
      addons:
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "L4nEr4rHuk4Le7jFQyAFNVsI+m7rsInUHPwhQMVPfUQq1gYdy2NzijLVY2Y/DMvmuxn0NgI/AN2b/FcY+qD8vWa4tz07BrRL5PAu+uISSQayVdKE7ELS8ENVrwGPIbpuk5RQpBVCpJOn1SbOmjSPcqHwfedLVt6cqAk/mCXbGBQd0As8YhGTDFwFtxXMD1TNwqpXCSLnUQKsatbtAb1BUH6erBCzTvFquevx70S/c0zv40gB1slla5MQwXrs14IQqJT05TQqJVgls5t4p+C4aZg0nZ3XRIGfpNyUkedod3cW7YW8UJX4brzFjqHyA2EiND3um9ov9aj7ZwRtmlavJs6w/cMS+eFBjAQmW3TZythe7oPYFZAc3c86KDQo0z9h836e7Sav/sGz/BvCpEa9ofTJJoROV8TobP2bWWFqoz0hPj3t8PDnuaoEuQeFdAh5ZjIuQ8OcGJrRMKoowqSWLiFs1XSUSvTU6f+Vhm7BWHuZc+FvmnpXxkJfG+0o4hzOSsQuspKhSrcy5bMJAi5rkxnkMheNKQBS8HZ6tpKwlJYVPX8gJQvfCwX6Z+Srfv22mPuWv/JpPG/NKPrxOHDa7aAQx6irGj+oDjucNmu0L9bkMhPuK3eNwtd6m0eoGAxDdq017gvY7EdczF00TbDNpwUDF4cqEeb7Fg5AQ5F48Tc="
      before_install:
        - curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-macosx.zip -o sonar-scanner-cli-3.3.0.1492-macosx.zip
        - unzip sonar-scanner-cli-3.3.0.1492-macosx.zip
        - export PATH=$(pwd)/sonar-scanner-3.3.0.1492-macosx/bin:$PATH
      before_script:
        - export CXX=clang++
      script:
        - build-wrapper-macosx-x86 --out-dir bw-output make platform=ios -j2 -C samples/
        - sonar-scanner -D sonar.projectKey=OuzelIOS -D sonar.projectName="Ouzel iOS" -D sonar.cfamily.threads=2 || true
    - name: tvOS
      compiler: clang
      os: osx
      osx_image: xcode7.3
      addons:
        sonarcloud:
          organization: "elnormous-github"
          token:
            secure: "L4nEr4rHuk4Le7jFQyAFNVsI+m7rsInUHPwhQMVPfUQq1gYdy2NzijLVY2Y/DMvmuxn0NgI/AN2b/FcY+qD8vWa4tz07BrRL5PAu+uISSQayVdKE7ELS8ENVrwGPIbpuk5RQpBVCpJOn1SbOmjSPcqHwfedLVt6cqAk/mCXbGBQd0As8YhGTDFwFtxXMD1TNwqpXCSLnUQKsatbtAb1BUH6erBCzTvFquevx70S/c0zv40gB1slla5MQwXrs14IQqJT05TQqJVgls5t4p+C4aZg0nZ3XRIGfpNyUkedod3cW7YW8UJX4brzFjqHyA2EiND3um9ov9aj7ZwRtmlavJs6w/cMS+eFBjAQmW3TZythe7oPYFZAc3c86KDQo0z9h836e7Sav/sGz/BvCpEa9ofTJJoROV8TobP2bWWFqoz0hPj3t8PDnuaoEuQeFdAh5ZjIuQ8OcGJrRMKoowqSWLiFs1XSUSvTU6f+Vhm7BWHuZc+FvmnpXxkJfG+0o4hzOSsQuspKhSrcy5bMJAi5rkxnkMheNKQBS8HZ6tpKwlJYVPX8gJQvfCwX6Z+Srfv22mPuWv/JpPG/NKPrxOHDa7aAQx6irGj+oDjucNmu0L9bkMhPuK3eNwtd6m0eoGAxDdq017gvY7EdczF00TbDNpwUDF4cqEeb7Fg5AQ5F48Tc="
      before_install:
        - curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.3.0.2102-macosx.zip -o sonar-scanner-cli-3.3.0.1492-macosx.zip
        - unzip sonar-scanner-cli-3.3.0.1492-macosx.zip
        - export PATH=$(pwd)/sonar-scanner-3.3.0.1492-macosx/bin:$PATH
      before_script:
        - export CXX=clang++
      script:
        - build-wrapper-macosx-x86 --out-dir bw-output make platform=tvos -j2 -C samples/
        - sonar-scanner -D sonar.projectKey=OuzelTVOS -D sonar.projectName="Ouzel tvOS" -D sonar.cfamily.threads=2 || true
    - name: Android
      language: android
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-26.0.0
          - android-26
      install:
        - yes | sdkmanager "ndk-bundle"
        - export ANDROID_NDK_HOME=/usr/local/android-sdk/ndk-bundle
      script:
        - $ANDROID_NDK_HOME/ndk-build -j2 -C samples/app/src/main/