trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo apt-get update --fix-missing
  - script: sudo apt-get install -y libgl1-mesa-dev libgles2-mesa-dev libopenal-dev libasound2-dev libxxf86vm-dev libxi-dev libxcursor-dev libxrandr-dev libxss-dev
  - script: |
      cd samples
      make -j2
    displayName: 'make'

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: PowerShell@2
    displayName: 'Install the Windows 8.1 SDK'
    inputs:
      targetType: 'inline'
      script: 'choco install windows-sdk-8.1'
  - task: MSBuild@1
    inputs:
      solution: samples/samples.vcxproj
      configuration: Release

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      cd samples
      make -j2
    displayName: 'make'
