trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: sudo apt-get update --fix-missing
  - script: sudo apt-get install -y libgl1-mesa-dev libgles2-mesa-dev libopenal-dev libasound2-dev libxxf86vm-dev libxi-dev libxcursor-dev libxrandr-dev libxss-dev
  - script: |
      cd samples
      make -j2
    displayName: 'make'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: MSBuild@1
    inputs:
      solution: samples/samples.vcxproj
      configuration: Release

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      cd samples
      make -j2
    displayName: 'make'
